# Generated by Django 6.0.2 on 2026-02-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_inmueble_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='esta_disponible',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('arrendada', 'Arrendada'), ('en_oferta', 'En oferta'), ('en_mantenimiento', 'En mantenimiento'), ('inactiva', 'Inactiva')], default='en_oferta', max_length=20),
        ),
    ]
