# Generated by Django 6.0.2 on 2026-03-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='banos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cocinas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='es_comercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='garajes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='habitaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='salas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
