# Generated by Django 6.0.2 on 2026-03-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_inmueble_banos_inmueble_cocinas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='administracion_incluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='en_conjunto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='valor_administracion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
