# Generated by Django 6.0.2 on 2026-03-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_inmueble_administracion_incluida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='enlace_google_maps',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
