# Generated by Django 6.0.2 on 2026-05-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0003_ticket_hu05_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='admin_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='admin_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='google_maps_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='in_complex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='living_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
