# Generated by Django 6.0.2 on 2026-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0005_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='damage_type',
            field=models.CharField(choices=[('PLUMBING', 'Plomería / Hidráulico'), ('ELECTRICITY', 'Electricidad'), ('LOCKSMITH', 'Cerrajería'), ('STRUCTURE', 'Estructura'), ('PAINTING', 'Pintura'), ('CARPENTRY', 'Carpintería'), ('APPLIANCE', 'Electrodoméstico'), ('OTHER', 'Otro')], default='OTHER', max_length=20),
        ),
    ]
