# Generated by Django 6.0.2 on 2026-06-01 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0006_alter_ticket_damage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ASSISTANT', 'Asistente Administrativo'), ('TENANT', 'Arrendatario'), ('TECHNICIAN', 'Técnico')], default='TENANT', max_length=20),
        ),
    ]
