# Generated by Django 6.0.2 on 2026-06-01 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0007_ticket_assigned_technician_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Ticket creado'), ('STATUS_CHANGE', 'Cambio de estado'), ('TECHNICIAN_ASSIGNED', 'Técnico asignado'), ('ATTACHMENT_ADDED', 'Adjunto agregado'), ('CONFIRMED', 'Reparación confirmada'), ('PROBLEM_REPORTED', 'Problema reportado'), ('COMPLETED_BY_TECHNICIAN', 'Completado por técnico'), ('CONTRACTOR_ASSIGNED', 'Contratista asignado')], max_length=30)),
                ('description', models.TextField()),
                ('old_value', models.CharField(blank=True, default='', max_length=200)),
                ('new_value', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_history_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pot.ticket')),
            ],
            options={
                'verbose_name_plural': 'ticket histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
