# Generated by Django 6.0.2 on 2026-06-09 23:41

from django.conf import settings
from django.db import migrations, models


def copy_technician_data(apps, schema_editor):
    Ticket = apps.get_model('pot', 'Ticket')
    for ticket in Ticket.objects.exclude(assigned_technician__isnull=True):
        ticket.assigned_technicians.add(ticket.assigned_technician)


def reverse_technician_data(apps, schema_editor):
    Ticket = apps.get_model('pot', 'Ticket')
    for ticket in Ticket.objects.all():
        first_tech = ticket.assigned_technicians.first()
        if first_tech:
            ticket.assigned_technician = first_tech
            ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0008_ticket_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_technicians',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'TECHNICIAN'}, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_technician_data, reverse_code=reverse_technician_data),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_technician',
        ),
    ]
