# Generated by Django 6.0.2 on 2026-06-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0009_remove_ticket_assigned_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'En registro'), ('PENDING_SIGNATURE', 'Pendiente de firma'), ('PENDING_APPROVAL', 'Pendiente de aprobación'), ('OBSERVATIONS_PENDING', 'Observaciones pendientes'), ('ACCEPTED', 'Aceptado'), ('CLOSED', 'Cerrado')], default='IN_PROGRESS', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='damage_type',
            field=models.CharField(choices=[('PLUMBING', 'Plomería / Hidráulico'), ('ELECTRICITY', 'Electricidad'), ('LOCKSMITH', 'Cerrajería'), ('STRUCTURE', 'Estructura'), ('PAINTING', 'Pintura'), ('CARPENTRY', 'Carpintería'), ('APPLIANCE', 'Electrodoméstico'), ('CLOSURE', 'Cierre de Contrato'), ('OTHER', 'Otro')], default='OTHER', max_length=20),
        ),
    ]
