# Generated by Django 6.0.2 on 2026-06-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0010_alter_inventory_status_alter_ticket_damage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='final_space_conditions',
            field=models.JSONField(blank=True, help_text='Condiciones finales de cada espacio registradas por el técnico al cerrar el contrato.', null=True),
        ),
    ]
