# Generated by Django 6.0.2 on 2026-06-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pot', '0011_add_final_space_conditions_to_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Abierto'), ('ACCEPTED', 'Aceptado'), ('IN_PROGRESS', 'En proceso'), ('PENDING_ADMIN', 'Pendiente de Admin'), ('PENDING_TENANT', 'Pendiente de Inquilino'), ('REJECTED', 'Rechazado'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20),
        ),
    ]
